#          ████
#      ████████████
#    ████████████████
#   █   ██████████   █     NexusBlock v@version@
#   ████   ████   ████     Original by xHyroM https://github.com/xHyroM/NexusBlock
#   ███████    ███████     Reworked by Sliide_ https://github.com/yiyoperez/NexusBlock
#   ████████  ████████
#     ██████  ██████       Wiki: nope
#        ███  ███          Support: nope
#          █  █            Something else..

# Do NOT touch!
config-version: 1

LEADERBOARD:
    LIMIT: 5
    EMPTY_TOP: "NONE"
    EMPTY_VALUE: 0
