# NexusBlock id.
ID: default

# Material
MATERIAL: DIAMOND_BLOCK

# Status
ENABLED: false

# Block max health.
HEALTH: 100

# Hologram height/y-offset.
HOLOGRAM-HEIGHT: 5

# Respawn nexus after destroy (in seconds)
RESPAWN_INTERVAL: 10

# Position of nexus
LOCATION:
    X: 10.0
    Y: 50.0
    Z: 10.0
    WORLD: "world"

# Hologram
# Available placeholders are
# %material%, %health%, %maxHealth% %top_1%, %top_2%, %value_1%, %value_2% etc..
HOLOGRAM:
    - "%material%"
    - "&b&lDIAMOND NEXUS"
    - "&cDestroy to get reward"
    - ""
    - "&a1 &7%top_1% &8| &7%value_1%"
    - "&a2 &7%top_2% &8| &7%value_2%"
    - "&a3 &7%top_3% &8| &7%value_3%"
    - ""
    - "&c%health%&8/&c%maxHealth%"

# Available placeholders are
# %player%, %destroys%
REWARDS:
    # Block location drops
    # Delete section to disable drop rewards.
    DROP:
        RADIUS: 5 # Value is in blocks.
        ACTIONS:
            - "[COMMAND] give %player% golden_apple 1"
    # Player that destroy block
    DESTROYER:
        - "give %player% golden_apple 1"
        - "say %player% destroyed block!"
        - "say %player% broke the nexus %destroys% times."
    # Set this section empty ( DESTROYERS: {} ) if you don't want give rewards to other destroyers.
    DESTROYERS:
        # First player (top 1)
        1:
            - "give %player% apple 1"
            - "say %player% broke the nexus %destroys% times."
        # Second player (top 2)
        2:
            - "give %player% book 1"
            - "say %player% broke the nexus %destroys% times."