# NexusBlock id.
ID: default

# Material
MATERIAL: DIAMOND_BLOCK

# Block max health.
HEALTH: 100

# Hologram height/y-offset.
HOLOGRAM-HEIGHT: 5

# Respawn nexus after destroy (in seconds)
RESPAWN_INTERVAL: 10

# Position of nexus
LOCATION:
    X: 10.0
    Y: 50.0
    Z: 10.0
    WORLD: "world"

# Hologram
# Available placeholders are
# %material%, %health%, %maxHealth% %top_1%, %top_2%, %value_1%, %value_2% etc..
HOLOGRAM:
    - "%material%"
    - "&b&lDIAMOND NEXUS"
    - "Destroy to get reward"
    - ""
    - "&a1 &7%top_1% &8| &7%value_1%"
    - "&a2 &7%top_2% &8| &7%value_2%"
    - "&a3 &7%top_3% &8| &7%value_3%"
    - ""
    - "&c%health%&8/&c%maxHealth%"

rewards:
    # First player (top 1)
    1:
        - "give {playerName} apple"
        - "say {playerName} {destroys} 1."
    # Second player (top 2)
    2:
        - "give {playerName} book"
        - "say {playerName} {destroys} 2."
    # Player that destroy block
    0:
        - "give {playerName} golden_apple"
        - "say {playerName} {destroys} destroyed block!!"