name: NexusBlock
version: @version@
main: xhyrom.nexusblock.NexusBlock
api-version: 1.13
authors: [ xHyroM, Sliide_ ]
description: Plugin that allows create nexus blocks.
softdepend:
    - HolographicDisplays
    - DecentHolograms
    - Holograms
    - Multiverse-Core
    - MultiWorld
    - My_Worlds

commands:
  nexusblock:
    description: Setup blocks or check informations
    aliases:
      - nb
      - blocknexus
