name: NexusBlock
version: @version@
main: xhyrom.nexusblock.NexusBlock
api-version: 1.13
authors: [ xHyroM, Sliide_]
softdepend:
  - HolographicDisplays
  - DecentHolograms
  - Holograms
  - Multiverse-Core
  - MultiWorld

commands:
  nexusblock:
    description: Setup blocks or check informations
    aliases:
      - nb
      - blocknexus
