name: NexusBlock
version: @version@
main: xhyrom.nexusblock.NexusBlock
api-version: 1.13
authors: [ xHyroM, Sliide_ ]
description: Plugin that allows create nexus blocks.
softdepend:
    - HolographicDisplays
    - DecentHolograms
    - Multiverse-Core
    - MultiWorld
    - My_Worlds

permissions:
    nexusblock.admin.break:
        default: op
        description: Allow the player to break placed nexus blocks when sneaking.