name: CI

on:
    push:
        branches: [ main , dev ]

jobs:
    releaseJar:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   uses: actions/setup-java@v4
                with:
                    java-version: 8
                    distribution: adopt
                    cache: gradle
            -   uses: actions/cache@v4
                with:
                    path: |
                        ~/.gradle/caches
                        ~/.gradle/wrapper
                    key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                    restore-keys: |
                        ${{ runner.os }}-gradle-
            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew
            -   name: Gradle build using ShadowJar
                run: ./gradlew clean shadowJar -s
            -   name: Upload Artifacts
                uses: actions/upload-artifact@v4
                with:
                    name: Artifacts
                    path: bin/*.jar